### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BabelDev0** [writeme-project/writeme#13]
We could move the license logic from the config files (package.json etc.) to searching for the actual license file.
So in the README, we can be sure to report the correct license with also the link to the file in the repo

**Comment by BabelDev0** [comment]
Issue License:
- [ ] - License file present
- [ ] - License present in configs but the file is missing
- [ ] - There is no file nor the configs, choose from the best licenses

**Comment by BabelDev0** [comment]
- [ ] Rethink logic where to put assemble_license. Flow: converter -> merger -> assembler
- [ ] Build the logic to put the right license: if fond the file and is not github repo, in that case seek for keywords in the file to detect the right license

**Comment by BabelDev0** [comment]
Logic: 
1. Config files are loaded with the license information.
2. One method checks if there is a license file inside the repo, if there is then I check if the repo is github, if so I put link, otherwise I search the found file for keywords to find the correct license
3. if in the merger all ConverterOutput have no license then I propose to the user to choose one, and once chosen we also create the file in the root of the repository

**Comment by BabelDev0** [comment]
https://github.com/writeme-project/writeme/wiki/License-logic

**Comment by ilcors-dev** [comment]
check licenses to add to the project, get them from [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

@ilcors-dev start from GNU to the bottom
@BabelDev0 start from GNU to the top

**Comment by ilcors-dev** [comment]
check lib https://github.com/Eolu/enum-assoc
