### ISSUE TITLE
capire come creare i package per le diverse distribuzioni

### ISSUE THREAD

**Issue by ilcors-dev** [writeme-project/writeme#14]
problema
vogliamo distribuire il software per più piattaforme ed archietture (eg: linux, windows, osx, osx arm) e farlo tramite i package manager disponibili:
- osx -> brew / altri
- linux -> apt / pacman / altri
- windows -> chocolatey / altri

il build dell'applicazione deve anche contenere tutti i file di template necessari a writeme per generare i readme file (techs.yaml, tutti i markdown ecc)

**Comment by BabelDev0** [comment]
Dovrei esserci riuscito 
```
brew install writeme
```

**Comment by BabelDev0** [comment]
Testiamo e chiudiamo la issue

- [ ] Leo test deb
- [ ] Luca test brew
