### ISSUE TITLE
How it works section in depth

### ISSUE THREAD

**Issue by ilcors-dev** [writeme-project/writeme#48]
Maybe we should add a section in the readme file of the project that illustrates a little bit deeper how the application works starting from the **parsing** of known config files, the **merging** of conflicting attributes and the **assembly** of the information gathered

**Comment by BabelDev0** [comment]
Good idea. I wrote something [here](https://github.com/writeme-project/writeme/wiki) that we can take a cue from, but in the README file maybe we want to have a more concise and direct writing style

**Comment by ilcors-dev** [comment]
sounds good, we could but a link in the readme file then

**Comment by BabelDev0** [comment]
Maybe I would write two concise lines and then put the link to the wiki to learn more. It might not be a bad idea to also include a GIF demo of what you could achieve with the program (eg https://github.com/kotartemiy/pygooglenews)
